### ISSUE TITLE
The requested URL /tools/rpki/validator3/rc/centos7/repo/rpki-validator-3.0-286.noarch.rpm was not found on this server.

### ISSUE THREAD

**Issue by schadom** [RIPE-NCC/rpki-validator-3-docker#2]
The URL `https://ftp.ripe.net/tools/rpki/validator3/rc/centos7/repo/rpki-validator-3.0-286.noarch.rpm` returns a 404. Maybe a rewrite rule or symbolic link for `/rpki-validator-latest.rpm` could be configured to avoid the necessity of updating the dockerfile on every new release. Thanks

**Comment by wibisono** [comment]
We've updated the image using the link to latest, so I assume this issue is resolved. Let us know otherwise.
